### ISSUE TITLE
Publication cache breaks on no title

### ISSUE THREAD

**Issue by haroldrubio** [openreview/openreview-expertise#119]
There are notes on OpenReview that do not have titles (https://openreview.net/forum?id=HyEqw2ZuWS) which causes an embedding to not get calculated and the API attempts to store an embedding of shape (0,) causing the following error. This may occur for publications with no abstracts.
```
Traceback (most recent call last):
  File "/home/openreview/miniconda3/envs/expertise/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/openreview/miniconda3/envs/expertise/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/openreview/openreview-expertise/expertise/service/celery_tasks.py", line 92, in run_expertise
    execute_expertise(config=config.to_json())
  File "/home/openreview/openreview-expertise/expertise/execute_expertise.py", line 151, in execute_expertise
    ens_predictor.embed_publications(
  File "/home/openreview/openreview-expertise/expertise/models/multifacet_recommender/ensemble.py", line 59, in embed_publications
    self.specter_predictor.embed_publications(specter_publications_path)
  File "/home/openreview/openreview-expertise/expertise/models/multifacet_recommender/specter.py", line 317, in embed_publications
    manager.run()
  File "/home/openreview/openreview-expertise/expertise/models/multifacet_recommender/specter.py", line 89, in run
    self._maybe_print_to_console_and_file(index, result, json.dumps(model_input_json))
  File "/home/openreview/openreview-expertise/expertise/models/multifacet_recommender/specter.py", line 108, in _maybe_print_to_console_and_file
    self._redis_con.tensorset(key=prediction_json['paper_id'], tensor=np.array(prediction_json['embedding']))
  File "/home/openreview/miniconda3/envs/expertise/lib/python3.8/site-packages/redisai/client.py", line 493, in tensorset
    res = self.execute_command(*args)
  File "/home/openreview/miniconda3/envs/expertise/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/openreview/miniconda3/envs/expertise/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/openreview/miniconda3/envs/expertise/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response

```

**Comment by purujitgoyal** [comment]
Specter skips the paper when the `title` is empty.

**Comment by melisabok** [comment]
Anyway it is more likely to be papers with no abstract than no title. I'm fine if Specter ignores them.

**Comment by purujitgoyal** [comment]
Okay. FYI, specter skips the paper when either `title` or `abstract` is empty.

**Comment by melisabok** [comment]
is this a decision from specter or us? why is this decision?

there are a lot of publications with no abstract and we need to keep using them for the expertise, with the title only.

**Comment by purujitgoyal** [comment]
It's the default setting of specter.

**Comment by purujitgoyal** [comment]
There's no way right now to control this. We will have to add a new custom predictor.

**Comment by carlosmondra** [comment]
Would it be too naive to simply copy the title into the abstract when the abstract is missing? I don't think there is a case where the title is missing and the title is present.
