### ISSUE TITLE
setup.py doesn't work as intended

### ISSUE THREAD

**Issue by kyunghyuncho** [openreview/openreview-expertise#25]
after running `python ./setup.py install` from the repo, i get the following error:
```
(base) kyunghyuncho-mbp:~ kyunghyuncho$ python -c 'import expertise'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kyunghyuncho/anaconda3/lib/python3.7/site-packages/openreview_expertise-0.1-py3.7.egg/expertise/__init__.py", line 1, in <module>
    from .core import *
  File "/Users/kyunghyuncho/anaconda3/lib/python3.7/site-packages/openreview_expertise-0.1-py3.7.egg/expertise/core.py", line 2, in <module>
    from . import models
ImportError: cannot import name 'models' from 'expertise' (/Users/kyunghyuncho/anaconda3/lib/python3.7/site-packages/openreview_expertise-0.1-py3.7.egg/expertise/__init__.py)
```

this doesn't happen if i simply add the repo path to `$PYTHONPATH`.

**Comment by kyunghyuncho** [comment]
tried it with `pip install openreview-expertise/' without success. i get the very same error. 

i'm using Mac OS X (10.14.6 (18G103)) with Anaconda (conda 4.6.14 and python 3.7.3).

**Comment by mspector** [comment]
Hmm... that's unexpected. I'll look into this soon.

**Comment by melisabok** [comment]
This is fixed here https://github.com/openreview/openreview-expertise/pull/28
