### ISSUE TITLE
SPECTER+MFR does not work without GPU

### ISSUE THREAD

**Issue by IvanStelmakh** [openreview/openreview-expertise#56]
I've tried to set up the SPECTER+MFR affinity computation without using GPU (by passing `cuda: false`)  in the config.jsonl but the code does seem to still expect some GPU. Please find the traceback:

```
Loading Archives dataset...
Loading Submissions dataset...
03/09/2021 17:29:52 - INFO - pytorch_transformers.modeling_bert -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
03/09/2021 17:29:52 - INFO - pytorch_transformers.modeling_xlnet -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
03/09/2021 17:29:52 - INFO - allennlp.common.registrable -   instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
03/09/2021 17:29:52 - INFO - allennlp.common.registrable -   instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
03/09/2021 17:29:52 - INFO - allennlp.common.registrable -   instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
03/09/2021 17:29:52 - INFO - allennlp.common.registrable -   instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
Setting SPECTER archives
Setting MultiFacetRecommender archives
Setting SPECTER submissions
Setting MultiFacetRecommender submissions
SPECTER:
Embedding publications...
03/09/2021 17:29:52 - INFO - allennlp.models.archival -   loading archive file ../specter/model.tar.gz
03/09/2021 17:29:52 - INFO - allennlp.models.archival -   extracting archive file ../specter/model.tar.gz to temp dir /tmp/tmp26lw9kok
03/09/2021 17:29:57 - INFO - allennlp.data.vocabulary -   Loading token dictionary from /tmp/tmp26lw9kok/vocabulary.
03/09/2021 17:29:57 - INFO - pytorch_pretrained_bert.modeling -   loading archive file ../specter/data/scibert_scivocab_uncased/scibert.tar.gz
03/09/2021 17:29:57 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file ../specter/data/scibert_scivocab_uncased/scibert.tar.gz to temp dir /tmp/tmpyvu2qhfx
03/09/2021 17:30:02 - INFO - pytorch_pretrained_bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 31090
}

03/09/2021 17:30:05 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file ../specter/data/scibert_scivocab_uncased/vocab.txt
  0%|                                                                                          | 0/2 [00:00<?, ?batches/s]03/09/2021 17:30:05 - WARNING - allennlp.data.fields.label_field -   Your label namespace was 'year'. We recommend you use a namespace ending with 'labels' or 'tags', so we don't add UNK and PAD tokens by default to your vocabulary.  See documentation for `non_padded_namespaces` parameter in Vocabulary.
3batches [00:05,  1.95s/batches]                                                                                          
MFR:
Featurizing publications...
7712 tokens before filtering <null>
Finish loading 37 sentences. While truncating 0 long sentences
Finish loading 37 sentences. While truncating 0 long sentences
39 tokens before filtering <null>
39 tokens before filtering <null>
Remove 0 empty items with no label
Loading data
Initializing model
OOV word type percentage: 99.99446422969757%
OOV token percentage: 100.0%
Randomly initializes embedding for  54190  words
Traceback (most recent call last):
  File "/home/istelmak/anaconda3/envs/expenv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/istelmak/anaconda3/envs/expenv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/projects/tir5/users/stiv/openreview/openreview-expertise-master/expertise/run.py", line 145, in <module>
    mfr_publications_path=None, skip_specter=config['model_params'].get('skip_specter', False))
  File "/projects/tir5/users/stiv/openreview/openreview-expertise-master/expertise/models/multifacet_recommender/ensemble.py", line 60, in embed_publications
    self.mfr_predictor.embed_publications(mfr_publications_path)
  File "/projects/tir5/users/stiv/openreview/openreview-expertise-master/expertise/models/multifacet_recommender/multifacet_recommender.py", line 720, in embed_publications
    extra_init_idx, self.encode_trans_layers, self.trans_nhid)
  File "/projects/tir5/users/stiv/openreview/openreview-expertise-master/expertise/models/multifacet_recommender/mfr_src/model.py", line 456, in __init__
    extra_init_emb = torch.randn(len(init_idx), ninp, requires_grad = False, device = device)
RuntimeError: Device index must not be negative 
```

**Comment by melisabok** [comment]
Thanks for reporting this, I'm running this model with a GPU with no issues. @ameyagodbole could you take a look and see what is missing?
